name: Testing

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Checking json format
      if: always()
      run: bash scripts/checkJsonFormat.sh

  hemtt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: HEMTT check
        run: hemtt check
